server:
  port: 0

spring:
  application:
    name: account-ws

  devtools:
    restart:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
  instance:
    instance-id:instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

gateway:
  ip: 127.0.0.1

