server:
  port: 8010

spring:
  application:
    name: DiscoveryService
#  security:
#    user:
#      name: test
#      password: test

eureka:
  client:
    registerWithEureka: false  #자기자신은 등록하지 않음
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
