server:
  port: 0
spring:
  application:
    name: see-ws
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  devtools:
    restart:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
  instance:
    instance-id:instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

gateway:
  ip: 172.23.192.1

