server:
  port: 8012

spring:
  application:
    name: ConfigServer
  profiles:
    active: native

  cloud:
    config:
      server:
        git:
          uri: https://github.com/0516khj2004/MyAppConfiguration.git
          username: 0516khj2004
          password: 522zx2796^^
          clone-on-start: true
        native:
          search-locations: file:///${user.home}/msa/msa/LAB/dev
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
